### ISSUE TITLE
Update SushiDocker

### ISSUE THREAD

**Issue by tbrand** [SushiCoinHQ/SushiCoin#102]
https://github.com/SushiCoinHQ/SushiDocker

1. Crystal version
2. Maybe it should have a default entry point or command

**Comment by kingsleyh** [comment]
The crystal version comes from docker hub - see here:

https://github.com/SushiCoinHQ/SushiDocker/blob/master/testnet/sushi/Dockerfile#L1

There are other tags available : https://hub.docker.com/r/crystallang/crystal/tags/

the tag called latest seems to be 24.1 still - which is a shame because it would be nice if we could just set it to latest and not worry about it.

But right now to get the latest version we would have to edit our Dockerfiles and use the tag `0.24.2`
instead

**Comment by tbrand** [comment]
It has newer version.
<img width="873" alt="2018-03-18 12 03 27" src="https://user-images.githubusercontent.com/3483230/37562160-65764a3a-2aa4-11e8-8958-42f7448df8af.png">

**Comment by kingsleyh** [comment]
I’ll upgrade it today

**Comment by kingsleyh** [comment]
I've upgraded to 0.24.2 now.
